##################
# Notify to email #
##################
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'techopschallenge@gmail.com'
  smtp_auth_username: 'techopschallenge@gmail.com'
  smtp_auth_password: 'Minecraft2018'

route:
  group_by: ['notif']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h 
  receiver: devops

  routes:
    - match:
        severity: critical
      receiver: devops

receivers:
- name: 'devops'
  email_configs:
  - to: 'zubayer@gmail.com'
